// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/invictoprojects/architecture-lab-3/server/balancers"
	"github.com/invictoprojects/architecture-lab-3/server/machines"
)

// Injectors from modules.go:

func ComposeApiServer(port HttpPortNumber) (*BalancersApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := balancers.NewStore(db)
	httpHandlerFunc := balancers.HttpHandler(store)
	machinesStore := machines.NewStore(db)
	machinesHttpHandlerFunc := machines.HttpHandler(machinesStore)
	balancersApiServer := &BalancersApiServer{
		Port:             port,
		BalancersHandler: httpHandlerFunc,
		MachinesHandler:  machinesHttpHandlerFunc,
	}
	return balancersApiServer, nil
}
